/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesServiceRouteImport } from './routes/services/$service'

const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/services/$service',
  path: '/services/$service',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/doctors': typeof DoctorsRoute
  '/gallery': typeof GalleryRoute
  '/pharmacy': typeof PharmacyRoute
  '/services/$service': typeof ServicesServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/doctors': typeof DoctorsRoute
  '/gallery': typeof GalleryRoute
  '/pharmacy': typeof PharmacyRoute
  '/services/$service': typeof ServicesServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/doctors': typeof DoctorsRoute
  '/gallery': typeof GalleryRoute
  '/pharmacy': typeof PharmacyRoute
  '/services/$service': typeof ServicesServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/departments'
    | '/doctors'
    | '/gallery'
    | '/pharmacy'
    | '/services/$service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/departments'
    | '/doctors'
    | '/gallery'
    | '/pharmacy'
    | '/services/$service'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/departments'
    | '/doctors'
    | '/gallery'
    | '/pharmacy'
    | '/services/$service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DoctorsRoute: typeof DoctorsRoute
  GalleryRoute: typeof GalleryRoute
  PharmacyRoute: typeof PharmacyRoute
  ServicesServiceRoute: typeof ServicesServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$service': {
      id: '/services/$service'
      path: '/services/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  DoctorsRoute: DoctorsRoute,
  GalleryRoute: GalleryRoute,
  PharmacyRoute: PharmacyRoute,
  ServicesServiceRoute: ServicesServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
